#!/bin/bash

OS=`uname -s`

if [ "$OS" == "Darwin" ]; then
  # macOS
  PKGDIR=~/Library/texmf/tex/latex/cartes
elif [ "$OS" == "Linux" ]; then
  # Debian
  PKGDIR=~/texmf/tex/latex/cartes
else
  echo "This OS is not supported."
  exit
fi

rm -rf $PKGDIR
mkdir -p $PKGDIR
cp *.code.tex *.sty $PKGDIR 
